project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: '/**/*.md'
    translation: '/%two_letters_code%/**/%original_file_name%'
    languages_mapping:
      two_letters_code:
        fr: fr
