project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: '**/*.md'
    ignore:
      - 'fr/**'
    translation: 'fr/%original_path%/%original_file_name%'
