project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: '**/*.md'
    ignore:
      - 'fr-FR/**'
      - 'es-ES/**'
      - 'de-DE/**'
    translation: '%locale%/%original_path%/%original_file_name%'
