name: Crowdin Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload sources to Crowdin and download translations
        uses: crowdin/github-action@v1.8.1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          push_translations: true
          config: 'crowdin.yml'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
