name: Crowdin Sync

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - 'crowdin.yml'
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Crowdin GitHub Action
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          push_translations: true
          config: 'crowdin.yml'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
